# Generated by Django 4.1.7 on 2023-03-15 07:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_mymodel_alter_competence_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('tools', models.CharField(max_length=200)),
                ('demo', models.URLField()),
                ('github', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
