# Generated by Django 4.1.7 on 2023-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScienceConsultingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('objective', models.TextField()),
                ('data_availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('timeline', models.CharField(choices=[('1_week', '1 Week'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months')], max_length=10)),
                ('additional_information', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
