# Generated by Django 4.1.7 on 2023-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_datascienceconsultingrequest_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboticProcessAutomationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('process_name', models.CharField(max_length=200)),
                ('process_description', models.TextField()),
                ('current_challenges', models.TextField()),
                ('estimated_time_savings', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_cost_savings', models.IntegerField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
