# Generated by Django 4.1.7 on 2023-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_tag_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('rpa', 'RPA'), ('data_management', 'Data Management')], max_length=50, unique=True),
        ),
    ]
