# Generated by Django 4.1.7 on 2023-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='info.tag'),
        ),
    ]
