# Generated by Django 4.1.7 on 2023-04-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Data Science', 'Data Science'), ('Robotic Process Automation', 'RPA'), ('Data Management', 'Data Management'), ('Data Engineering', 'Data Engineering'), ('Business Analysis', 'Business Analysis'), ('Process Automation', 'Process Automation'), ('Machine Learning', 'Machine Learning'), ('Software Development', 'Software Development')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='project_videos/')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.project')),
            ],
        ),
    ]
