# Generated by Django 4.1.7 on 2023-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
