# Generated by Django 4.2.3 on 2023-09-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='external_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
